### ISSUE TITLE
Script for PI notification

### ISSUE THREAD

**Issue by hettlage** [saltastroops/data-archive-database#107]
There should be a script which emails PIs if their data becomes publicly available soon.

The script should remember which email notifications have been sent, so that it can be re-run without notifying the PI again.

**Comment by Eb-Zeero** [comment]
Is this a data archive problem to solve?
data archive do not have SALT's users contact details

**Comment by hettlage** [comment]
As this script is about ensuring data integrity in the data archive, I'd argue it is a data archive problem.

**Comment by hettlage** [comment]
Oh sorry, I thought that was about another issue.

This is only sort-of a data archive issue. But I wanted to put it somewhere. :)
