### ISSUE TITLE
refer to the database schema in queries

### ISSUE THREAD

**Issue by Lonwabo11** [saltastroops/data-archive-database#173]
The files ssda.py and hrs_observation_properties.py do not refer to the schema first before using a table. Example: observations.artifact, the table name is just used hence it raises a relation error. These files may not be the only ones though.

**Comment by saltastroops** [comment]
A possible solution should be to set the search path for the database; see https://stackoverflow.com/questions/2875610/permanently-set-postgresql-schema-path.

**Comment by hettlage** [comment]
Should be covered by the V5 flyway file.
