### ISSUE TITLE
Salticam filter file B-S1 missing

### ISSUE THREAD

**Issue by hettlage** [saltastroops/data-archive-database#27]
There is no file src/ssda/data/salticam/B-S1.txt.

**Comment by hettlage** [comment]
That might not be the only missing filter. I think I came across a missing R-S1 as well.

**Comment by chynamyerz** [comment]
Yes, we mentioned this and it was said to ask Lisa if she has any information about the missing filters.

**Comment by chynamyerz** [comment]
Since the code in the development branch is not updated, it was challenging to resolve this issue separately. It is resolved in the salt-observation branch instead.

**Comment by chynamyerz** [comment]
Resolved
