### ISSUE TITLE
Map both raw and product data

### ISSUE THREAD

**Issue by hettlage** [saltastroops/data-archive-database#41]
Both raw and product data files should be mapped to the database. To this end

- A lookup table ("calibration_level") has to be added, with values RAW and REDUCED.

- A calibration_level field referencing that table has to be added to the artifact table.

- For every product file the script must check whether there is a corresponding raw file. If there is, an additional artifact entry has to be created for that file.

**Comment by chynamyerz** [comment]
I think this issue is going to be resolved by issue #44
