### ISSUE TITLE
PROPID values not handled properly

### ISSUE THREAD

**Issue by hettlage** [saltastroops/data-archive-database#57]
We have "PROPID" values that are not taken of.

CAL_STABLE
CAL_GAIN
UNKNOWN

**Comment by Eb-Zeero** [comment]
Need to confirm with Ros what to do with this.

**Comment by chynamyerz** [comment]
CAL_STABLE is for the Internal Arc,

CAL_GAIN & UNKNOWN are to be excluded for now
