### ISSUE TITLE
Wrong product type for standards

### ISSUE THREAD

**Issue by hettlage** [saltastroops/data-archive-database#73]
It seems that some HRS observations are stored with product type Science even though they are standardsa.

An example is R201905310019.fits.

**Comment by chynamyerz** [comment]
I have investigated this file, it has the following properties which I believe are misleading.

BVISITID = empty
PROPID = CAL_RVST

But!

OBSTYPE = Science
OBJECT = HD 1461

**Comment by chynamyerz** [comment]
The pending pull request fixes this issue.
